package travel.impl;

import travel.*;


import java.net.URI;
import java.io.Serializable;
import javax.jdo.annotations.Embedded;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultContact <br>
 * @version generated on Sun May 16 18:22:29 IST 2021 by ayushyadav
 */
@Entity
 public class DefaultContact extends WrappedIndividualImpl implements Contact , Serializable {
	 private static final long serialVersionUID = 1L;
	 @GeneratedValue
	 private long id;
	 @Id 
	 private String name;

private Collection < ? extends String > HasCity ; ;
private Collection < ? extends String > HasEMail ; ;
private Collection < ? extends String > HasStreet ; ;
private Collection < ? extends Integer > HasZipCode ;

    public DefaultContact(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
	name = iri.toString();
	
	HasCity= getHasCity();
	HasEMail= getHasEMail();
	HasStreet= getHasStreet();
	HasZipCode= getHasZipCode();
    }





    /* ***************************************************
     * Data Property http://www.owl-ontologies.com/travel.owl#hasCity
     */
     
    public Collection<? extends String> getHasCity() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASCITY, String.class);
    }

    public boolean hasHasCity() {
		return !getHasCity().isEmpty();
    }

    public void addHasCity(String newHasCity) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASCITY, newHasCity);
    }

    public void removeHasCity(String oldHasCity) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASCITY, oldHasCity);
    }


    /* ***************************************************
     * Data Property http://www.owl-ontologies.com/travel.owl#hasEMail
     */
     
    public Collection<? extends String> getHasEMail() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASEMAIL, String.class);
    }

    public boolean hasHasEMail() {
		return !getHasEMail().isEmpty();
    }

    public void addHasEMail(String newHasEMail) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASEMAIL, newHasEMail);
    }

    public void removeHasEMail(String oldHasEMail) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASEMAIL, oldHasEMail);
    }


    /* ***************************************************
     * Data Property http://www.owl-ontologies.com/travel.owl#hasStreet
     */
     
    public Collection<? extends String> getHasStreet() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASSTREET, String.class);
    }

    public boolean hasHasStreet() {
		return !getHasStreet().isEmpty();
    }

    public void addHasStreet(String newHasStreet) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASSTREET, newHasStreet);
    }

    public void removeHasStreet(String oldHasStreet) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASSTREET, oldHasStreet);
    }


    /* ***************************************************
     * Data Property http://www.owl-ontologies.com/travel.owl#hasZipCode
     */
     
    public Collection<? extends Integer> getHasZipCode() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASZIPCODE, Integer.class);
    }

    public boolean hasHasZipCode() {
		return !getHasZipCode().isEmpty();
    }

    public void addHasZipCode(Integer newHasZipCode) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASZIPCODE, newHasZipCode);
    }

    public void removeHasZipCode(Integer oldHasZipCode) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASZIPCODE, oldHasZipCode);
    }


}
