package camera;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: BodyWithNonAdjustableShutterSpeed <br>
 * @version generated on Sun May 16 18:13:09 IST 2021 by ayushyadav
 */

public interface BodyWithNonAdjustableShutterSpeed extends Body {

    /* ***************************************************
     * Property http://www.xfront.com/owl/ontologies/camera/#cost
     */
     
    /**
     * Gets all property values for the cost property.<p>
     * 
     * @returns a collection of values for the cost property.
     */
    Collection<? extends Money> getCost();

    /**
     * Checks if the class has a cost property value.<p>
     * 
     * @return true if there is a cost property value.
     */
    boolean hasCost();

    /**
     * Adds a cost property value.<p>
     * 
     * @param newCost the cost property value to be added
     */
    void addCost(Money newCost);

    /**
     * Removes a cost property value.<p>
     * 
     * @param oldCost the cost property value to be removed.
     */
    void removeCost(Money oldCost);


    /* ***************************************************
     * Property http://www.xfront.com/owl/ontologies/camera/#shutter-speed
     */
     
    /**
     * Gets all property values for the shutter_speed property.<p>
     * 
     * @returns a collection of values for the shutter_speed property.
     */
    Collection<? extends Range> getShutter_speed();

    /**
     * Checks if the class has a shutter_speed property value.<p>
     * 
     * @return true if there is a shutter_speed property value.
     */
    boolean hasShutter_speed();

    /**
     * Adds a shutter_speed property value.<p>
     * 
     * @param newShutter_speed the shutter_speed property value to be added
     */
    void addShutter_speed(Range newShutter_speed);

    /**
     * Removes a shutter_speed property value.<p>
     * 
     * @param oldShutter_speed the shutter_speed property value to be removed.
     */
    void removeShutter_speed(Range oldShutter_speed);


    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
