package camera;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Large_Format <br>
 * @version generated on Sun May 16 18:13:09 IST 2021 by ayushyadav
 */

public interface Large_Format extends Camera {

    /* ***************************************************
     * Property http://www.xfront.com/owl/ontologies/camera/#body
     */
     
    /**
     * Gets all property values for the body property.<p>
     * 
     * @returns a collection of values for the body property.
     */
    Collection<? extends Body> getBody();

    /**
     * Checks if the class has a body property value.<p>
     * 
     * @return true if there is a body property value.
     */
    boolean hasBody();

    /**
     * Adds a body property value.<p>
     * 
     * @param newBody the body property value to be added
     */
    void addBody(Body newBody);

    /**
     * Removes a body property value.<p>
     * 
     * @param oldBody the body property value to be removed.
     */
    void removeBody(Body oldBody);


    /* ***************************************************
     * Property http://www.xfront.com/owl/ontologies/camera/#cost
     */
     
    /**
     * Gets all property values for the cost property.<p>
     * 
     * @returns a collection of values for the cost property.
     */
    Collection<? extends Money> getCost();

    /**
     * Checks if the class has a cost property value.<p>
     * 
     * @return true if there is a cost property value.
     */
    boolean hasCost();

    /**
     * Adds a cost property value.<p>
     * 
     * @param newCost the cost property value to be added
     */
    void addCost(Money newCost);

    /**
     * Removes a cost property value.<p>
     * 
     * @param oldCost the cost property value to be removed.
     */
    void removeCost(Money oldCost);


    /* ***************************************************
     * Property http://www.xfront.com/owl/ontologies/camera/#lens
     */
     
    /**
     * Gets all property values for the lens property.<p>
     * 
     * @returns a collection of values for the lens property.
     */
    Collection<? extends Lens> getLens();

    /**
     * Checks if the class has a lens property value.<p>
     * 
     * @return true if there is a lens property value.
     */
    boolean hasLens();

    /**
     * Adds a lens property value.<p>
     * 
     * @param newLens the lens property value to be added
     */
    void addLens(Lens newLens);

    /**
     * Removes a lens property value.<p>
     * 
     * @param oldLens the lens property value to be removed.
     */
    void removeLens(Lens oldLens);


    /* ***************************************************
     * Property http://www.xfront.com/owl/ontologies/camera/#viewFinder
     */
     
    /**
     * Gets all property values for the viewFinder property.<p>
     * 
     * @returns a collection of values for the viewFinder property.
     */
    Collection<? extends Viewer> getViewFinder();

    /**
     * Checks if the class has a viewFinder property value.<p>
     * 
     * @return true if there is a viewFinder property value.
     */
    boolean hasViewFinder();

    /**
     * Adds a viewFinder property value.<p>
     * 
     * @param newViewFinder the viewFinder property value to be added
     */
    void addViewFinder(Viewer newViewFinder);

    /**
     * Removes a viewFinder property value.<p>
     * 
     * @param oldViewFinder the viewFinder property value to be removed.
     */
    void removeViewFinder(Viewer oldViewFinder);


    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
