package camera;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Money <br>
 * @version generated on Sun May 16 18:13:09 IST 2021 by ayushyadav
 */

public interface Money extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.xfront.com/owl/ontologies/camera/#currency
     */
     
    /**
     * Gets all property values for the currency property.<p>
     * 
     * @returns a collection of values for the currency property.
     */
    Collection<? extends String> getCurrency();

    /**
     * Checks if the class has a currency property value.<p>
     * 
     * @return true if there is a currency property value.
     */
    boolean hasCurrency();

    /**
     * Adds a currency property value.<p>
     * 
     * @param newCurrency the currency property value to be added
     */
    void addCurrency(String newCurrency);

    /**
     * Removes a currency property value.<p>
     * 
     * @param oldCurrency the currency property value to be removed.
     */
    void removeCurrency(String oldCurrency);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
