package camera;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: PurchaseableItem <br>
 * @version generated on Sun May 16 18:13:09 IST 2021 by ayushyadav
 */

public interface PurchaseableItem extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.xfront.com/owl/ontologies/camera/#cost
     */
     
    /**
     * Gets all property values for the cost property.<p>
     * 
     * @returns a collection of values for the cost property.
     */
    Collection<? extends Money> getCost();

    /**
     * Checks if the class has a cost property value.<p>
     * 
     * @return true if there is a cost property value.
     */
    boolean hasCost();

    /**
     * Adds a cost property value.<p>
     * 
     * @param newCost the cost property value to be added
     */
    void addCost(Money newCost);

    /**
     * Removes a cost property value.<p>
     * 
     * @param oldCost the cost property value to be removed.
     */
    void removeCost(Money oldCost);


    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
