package camera;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Range <br>
 * @version generated on Sun May 16 18:13:09 IST 2021 by ayushyadav
 */

public interface Range extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.xfront.com/owl/ontologies/camera/#max
     */
     
    /**
     * Gets all property values for the max property.<p>
     * 
     * @returns a collection of values for the max property.
     */
    Collection<? extends Float> getMax();

    /**
     * Checks if the class has a max property value.<p>
     * 
     * @return true if there is a max property value.
     */
    boolean hasMax();

    /**
     * Adds a max property value.<p>
     * 
     * @param newMax the max property value to be added
     */
    void addMax(Float newMax);

    /**
     * Removes a max property value.<p>
     * 
     * @param oldMax the max property value to be removed.
     */
    void removeMax(Float oldMax);



    /* ***************************************************
     * Property http://www.xfront.com/owl/ontologies/camera/#min
     */
     
    /**
     * Gets all property values for the min property.<p>
     * 
     * @returns a collection of values for the min property.
     */
    Collection<? extends Float> getMin();

    /**
     * Checks if the class has a min property value.<p>
     * 
     * @return true if there is a min property value.
     */
    boolean hasMin();

    /**
     * Adds a min property value.<p>
     * 
     * @param newMin the min property value to be added
     */
    void addMin(Float newMin);

    /**
     * Removes a min property value.<p>
     * 
     * @param oldMin the min property value to be removed.
     */
    void removeMin(Float oldMin);



    /* ***************************************************
     * Property http://www.xfront.com/owl/ontologies/camera/#units
     */
     
    /**
     * Gets all property values for the units property.<p>
     * 
     * @returns a collection of values for the units property.
     */
    Collection<? extends String> getUnits();

    /**
     * Checks if the class has a units property value.<p>
     * 
     * @return true if there is a units property value.
     */
    boolean hasUnits();

    /**
     * Adds a units property value.<p>
     * 
     * @param newUnits the units property value to be added
     */
    void addUnits(String newUnits);

    /**
     * Removes a units property value.<p>
     * 
     * @param oldUnits the units property value to be removed.
     */
    void removeUnits(String oldUnits);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
