package camera;



import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Sun May 16 18:13:09 IST 2021 by ayushyadav
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://www.xfront.com/owl/ontologies/camera/#Body
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BODY.<p>
     * 
     */
    public static final OWLClass CLASS_BODY = factory.getOWLClass(IRI.create("http://www.xfront.com/owl/ontologies/camera/#Body"));

    /* ***************************************************
     * Class http://www.xfront.com/owl/ontologies/camera/#BodyWithNonAdjustableShutterSpeed
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BODYWITHNONADJUSTABLESHUTTERSPEED.<p>
     * 
     */
    public static final OWLClass CLASS_BODYWITHNONADJUSTABLESHUTTERSPEED = factory.getOWLClass(IRI.create("http://www.xfront.com/owl/ontologies/camera/#BodyWithNonAdjustableShutterSpeed"));

    /* ***************************************************
     * Class http://www.xfront.com/owl/ontologies/camera/#Camera
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CAMERA.<p>
     * 
     */
    public static final OWLClass CLASS_CAMERA = factory.getOWLClass(IRI.create("http://www.xfront.com/owl/ontologies/camera/#Camera"));

    /* ***************************************************
     * Class http://www.xfront.com/owl/ontologies/camera/#Digital
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DIGITAL.<p>
     * 
     */
    public static final OWLClass CLASS_DIGITAL = factory.getOWLClass(IRI.create("http://www.xfront.com/owl/ontologies/camera/#Digital"));

    /* ***************************************************
     * Class http://www.xfront.com/owl/ontologies/camera/#Large-Format
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LARGE_FORMAT.<p>
     * 
     */
    public static final OWLClass CLASS_LARGE_FORMAT = factory.getOWLClass(IRI.create("http://www.xfront.com/owl/ontologies/camera/#Large-Format"));

    /* ***************************************************
     * Class http://www.xfront.com/owl/ontologies/camera/#Lens
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LENS.<p>
     * 
     */
    public static final OWLClass CLASS_LENS = factory.getOWLClass(IRI.create("http://www.xfront.com/owl/ontologies/camera/#Lens"));

    /* ***************************************************
     * Class http://www.xfront.com/owl/ontologies/camera/#Money
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MONEY.<p>
     * 
     */
    public static final OWLClass CLASS_MONEY = factory.getOWLClass(IRI.create("http://www.xfront.com/owl/ontologies/camera/#Money"));

    /* ***************************************************
     * Class http://www.xfront.com/owl/ontologies/camera/#PurchaseableItem
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PURCHASEABLEITEM.<p>
     * 
     */
    public static final OWLClass CLASS_PURCHASEABLEITEM = factory.getOWLClass(IRI.create("http://www.xfront.com/owl/ontologies/camera/#PurchaseableItem"));

    /* ***************************************************
     * Class http://www.xfront.com/owl/ontologies/camera/#Range
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RANGE.<p>
     * 
     */
    public static final OWLClass CLASS_RANGE = factory.getOWLClass(IRI.create("http://www.xfront.com/owl/ontologies/camera/#Range"));

    /* ***************************************************
     * Class http://www.xfront.com/owl/ontologies/camera/#SLR
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SLR.<p>
     * 
     */
    public static final OWLClass CLASS_SLR = factory.getOWLClass(IRI.create("http://www.xfront.com/owl/ontologies/camera/#SLR"));

    /* ***************************************************
     * Class http://www.xfront.com/owl/ontologies/camera/#Viewer
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class VIEWER.<p>
     * 
     */
    public static final OWLClass CLASS_VIEWER = factory.getOWLClass(IRI.create("http://www.xfront.com/owl/ontologies/camera/#Viewer"));

    /* ***************************************************
     * Class http://www.xfront.com/owl/ontologies/camera/#Window
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class WINDOW.<p>
     * 
     */
    public static final OWLClass CLASS_WINDOW = factory.getOWLClass(IRI.create("http://www.xfront.com/owl/ontologies/camera/#Window"));

    /* ***************************************************
     * Object Property http://www.xfront.com/owl/ontologies/camera/#body
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property BODY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_BODY = factory.getOWLObjectProperty(IRI.create("http://www.xfront.com/owl/ontologies/camera/#body"));

    /* ***************************************************
     * Object Property http://www.xfront.com/owl/ontologies/camera/#compatibleWith
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property COMPATIBLEWITH.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_COMPATIBLEWITH = factory.getOWLObjectProperty(IRI.create("http://www.xfront.com/owl/ontologies/camera/#compatibleWith"));

    /* ***************************************************
     * Object Property http://www.xfront.com/owl/ontologies/camera/#cost
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property COST.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_COST = factory.getOWLObjectProperty(IRI.create("http://www.xfront.com/owl/ontologies/camera/#cost"));

    /* ***************************************************
     * Object Property http://www.xfront.com/owl/ontologies/camera/#lens
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property LENS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_LENS = factory.getOWLObjectProperty(IRI.create("http://www.xfront.com/owl/ontologies/camera/#lens"));

    /* ***************************************************
     * Object Property http://www.xfront.com/owl/ontologies/camera/#part
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property PART.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_PART = factory.getOWLObjectProperty(IRI.create("http://www.xfront.com/owl/ontologies/camera/#part"));

    /* ***************************************************
     * Object Property http://www.xfront.com/owl/ontologies/camera/#shutter-speed
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property SHUTTER_SPEED.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_SHUTTER_SPEED = factory.getOWLObjectProperty(IRI.create("http://www.xfront.com/owl/ontologies/camera/#shutter-speed"));

    /* ***************************************************
     * Object Property http://www.xfront.com/owl/ontologies/camera/#viewFinder
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property VIEWFINDER.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_VIEWFINDER = factory.getOWLObjectProperty(IRI.create("http://www.xfront.com/owl/ontologies/camera/#viewFinder"));

    /* ***************************************************
     * Data Property http://www.xfront.com/owl/ontologies/camera/#aperture
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property APERTURE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_APERTURE = factory.getOWLDataProperty(IRI.create("http://www.xfront.com/owl/ontologies/camera/#aperture"));

    /* ***************************************************
     * Data Property http://www.xfront.com/owl/ontologies/camera/#currency
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property CURRENCY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_CURRENCY = factory.getOWLDataProperty(IRI.create("http://www.xfront.com/owl/ontologies/camera/#currency"));

    /* ***************************************************
     * Data Property http://www.xfront.com/owl/ontologies/camera/#f-stop
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property F_STOP.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_F_STOP = factory.getOWLDataProperty(IRI.create("http://www.xfront.com/owl/ontologies/camera/#f-stop"));

    /* ***************************************************
     * Data Property http://www.xfront.com/owl/ontologies/camera/#focal-length
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property FOCAL_LENGTH.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_FOCAL_LENGTH = factory.getOWLDataProperty(IRI.create("http://www.xfront.com/owl/ontologies/camera/#focal-length"));

    /* ***************************************************
     * Data Property http://www.xfront.com/owl/ontologies/camera/#max
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property MAX.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_MAX = factory.getOWLDataProperty(IRI.create("http://www.xfront.com/owl/ontologies/camera/#max"));

    /* ***************************************************
     * Data Property http://www.xfront.com/owl/ontologies/camera/#min
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property MIN.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_MIN = factory.getOWLDataProperty(IRI.create("http://www.xfront.com/owl/ontologies/camera/#min"));

    /* ***************************************************
     * Data Property http://www.xfront.com/owl/ontologies/camera/#size
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property SIZE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_SIZE = factory.getOWLDataProperty(IRI.create("http://www.xfront.com/owl/ontologies/camera/#size"));

    /* ***************************************************
     * Data Property http://www.xfront.com/owl/ontologies/camera/#units
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property UNITS.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_UNITS = factory.getOWLDataProperty(IRI.create("http://www.xfront.com/owl/ontologies/camera/#units"));


}
