package people;



import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Sun May 16 17:26:14 IST 2021 by ayushyadav
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#adult
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ADULT.<p>
     * 
     */
    public static final OWLClass CLASS_ADULT = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#adult"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#animal
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ANIMAL.<p>
     * 
     */
    public static final OWLClass CLASS_ANIMAL = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#animal"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#animal_lover
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ANIMAL_LOVER.<p>
     * 
     */
    public static final OWLClass CLASS_ANIMAL_LOVER = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#animal_lover"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#bicycle
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BICYCLE.<p>
     * 
     */
    public static final OWLClass CLASS_BICYCLE = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#bicycle"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#bone
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BONE.<p>
     * 
     */
    public static final OWLClass CLASS_BONE = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#bone"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#brain
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BRAIN.<p>
     * 
     */
    public static final OWLClass CLASS_BRAIN = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#brain"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#broadsheet
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BROADSHEET.<p>
     * 
     */
    public static final OWLClass CLASS_BROADSHEET = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#broadsheet"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#bus
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BUS.<p>
     * 
     */
    public static final OWLClass CLASS_BUS = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#bus"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#bus_company
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BUS_COMPANY.<p>
     * 
     */
    public static final OWLClass CLASS_BUS_COMPANY = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#bus_company"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#bus_driver
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BUS_DRIVER.<p>
     * 
     */
    public static final OWLClass CLASS_BUS_DRIVER = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#bus_driver"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#car
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CAR.<p>
     * 
     */
    public static final OWLClass CLASS_CAR = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#car"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#cat
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CAT.<p>
     * 
     */
    public static final OWLClass CLASS_CAT = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#cat"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#cat_liker
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CAT_LIKER.<p>
     * 
     */
    public static final OWLClass CLASS_CAT_LIKER = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#cat_liker"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#cat_owner
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CAT_OWNER.<p>
     * 
     */
    public static final OWLClass CLASS_CAT_OWNER = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#cat_owner"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#company
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class COMPANY.<p>
     * 
     */
    public static final OWLClass CLASS_COMPANY = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#company"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#cow
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class COW.<p>
     * 
     */
    public static final OWLClass CLASS_COW = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#cow"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#dog
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DOG.<p>
     * 
     */
    public static final OWLClass CLASS_DOG = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#dog"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#dog_liker
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DOG_LIKER.<p>
     * 
     */
    public static final OWLClass CLASS_DOG_LIKER = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#dog_liker"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#dog_owner
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DOG_OWNER.<p>
     * 
     */
    public static final OWLClass CLASS_DOG_OWNER = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#dog_owner"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#driver
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DRIVER.<p>
     * 
     */
    public static final OWLClass CLASS_DRIVER = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#driver"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#duck
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DUCK.<p>
     * 
     */
    public static final OWLClass CLASS_DUCK = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#duck"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#elderly
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ELDERLY.<p>
     * 
     */
    public static final OWLClass CLASS_ELDERLY = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#elderly"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#female
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FEMALE.<p>
     * 
     */
    public static final OWLClass CLASS_FEMALE = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#female"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#giraffe
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GIRAFFE.<p>
     * 
     */
    public static final OWLClass CLASS_GIRAFFE = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#giraffe"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#grass
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GRASS.<p>
     * 
     */
    public static final OWLClass CLASS_GRASS = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#grass"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#grownup
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GROWNUP.<p>
     * 
     */
    public static final OWLClass CLASS_GROWNUP = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#grownup"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#haulage_company
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HAULAGE_COMPANY.<p>
     * 
     */
    public static final OWLClass CLASS_HAULAGE_COMPANY = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#haulage_company"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#haulage_truck_driver
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HAULAGE_TRUCK_DRIVER.<p>
     * 
     */
    public static final OWLClass CLASS_HAULAGE_TRUCK_DRIVER = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#haulage_truck_driver"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#haulage_worker
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HAULAGE_WORKER.<p>
     * 
     */
    public static final OWLClass CLASS_HAULAGE_WORKER = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#haulage_worker"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#kid
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class KID.<p>
     * 
     */
    public static final OWLClass CLASS_KID = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#kid"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#leaf
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LEAF.<p>
     * 
     */
    public static final OWLClass CLASS_LEAF = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#leaf"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#lorry
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LORRY.<p>
     * 
     */
    public static final OWLClass CLASS_LORRY = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#lorry"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#lorry_driver
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LORRY_DRIVER.<p>
     * 
     */
    public static final OWLClass CLASS_LORRY_DRIVER = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#lorry_driver"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#mad_cow
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MAD_COW.<p>
     * 
     */
    public static final OWLClass CLASS_MAD_COW = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#mad_cow"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#magazine
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MAGAZINE.<p>
     * 
     */
    public static final OWLClass CLASS_MAGAZINE = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#magazine"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#male
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MALE.<p>
     * 
     */
    public static final OWLClass CLASS_MALE = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#male"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#man
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MAN.<p>
     * 
     */
    public static final OWLClass CLASS_MAN = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#man"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#newspaper
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NEWSPAPER.<p>
     * 
     */
    public static final OWLClass CLASS_NEWSPAPER = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#newspaper"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#old_lady
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class OLD_LADY.<p>
     * 
     */
    public static final OWLClass CLASS_OLD_LADY = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#old_lady"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#person
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PERSON.<p>
     * 
     */
    public static final OWLClass CLASS_PERSON = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#person"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#pet
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PET.<p>
     * 
     */
    public static final OWLClass CLASS_PET = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#pet"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#pet_owner
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PET_OWNER.<p>
     * 
     */
    public static final OWLClass CLASS_PET_OWNER = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#pet_owner"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#plant
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PLANT.<p>
     * 
     */
    public static final OWLClass CLASS_PLANT = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#plant"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#publication
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PUBLICATION.<p>
     * 
     */
    public static final OWLClass CLASS_PUBLICATION = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#publication"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#quality_broadsheet
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class QUALITY_BROADSHEET.<p>
     * 
     */
    public static final OWLClass CLASS_QUALITY_BROADSHEET = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#quality_broadsheet"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#red_top
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RED_TOP.<p>
     * 
     */
    public static final OWLClass CLASS_RED_TOP = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#red_top"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#sheep
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SHEEP.<p>
     * 
     */
    public static final OWLClass CLASS_SHEEP = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#sheep"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#tabloid
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TABLOID.<p>
     * 
     */
    public static final OWLClass CLASS_TABLOID = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#tabloid"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#tiger
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TIGER.<p>
     * 
     */
    public static final OWLClass CLASS_TIGER = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#tiger"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#tree
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TREE.<p>
     * 
     */
    public static final OWLClass CLASS_TREE = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#tree"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#truck
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TRUCK.<p>
     * 
     */
    public static final OWLClass CLASS_TRUCK = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#truck"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#van
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class VAN.<p>
     * 
     */
    public static final OWLClass CLASS_VAN = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#van"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#van_driver
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class VAN_DRIVER.<p>
     * 
     */
    public static final OWLClass CLASS_VAN_DRIVER = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#van_driver"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#vegetarian
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class VEGETARIAN.<p>
     * 
     */
    public static final OWLClass CLASS_VEGETARIAN = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#vegetarian"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#vehicle
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class VEHICLE.<p>
     * 
     */
    public static final OWLClass CLASS_VEHICLE = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#vehicle"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#white_thing
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class WHITE_THING.<p>
     * 
     */
    public static final OWLClass CLASS_WHITE_THING = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#white_thing"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#white_van_man
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class WHITE_VAN_MAN.<p>
     * 
     */
    public static final OWLClass CLASS_WHITE_VAN_MAN = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#white_van_man"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#woman
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class WOMAN.<p>
     * 
     */
    public static final OWLClass CLASS_WOMAN = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#woman"));

    /* ***************************************************
     * Class http://owl.man.ac.uk/2006/07/sssw/people#young
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class YOUNG.<p>
     * 
     */
    public static final OWLClass CLASS_YOUNG = factory.getOWLClass(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#young"));

    /* ***************************************************
     * Object Property http://owl.man.ac.uk/2006/07/sssw/people#drives
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property DRIVES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_DRIVES = factory.getOWLObjectProperty(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#drives"));

    /* ***************************************************
     * Object Property http://owl.man.ac.uk/2006/07/sssw/people#eaten_by
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property EATEN_BY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_EATEN_BY = factory.getOWLObjectProperty(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#eaten_by"));

    /* ***************************************************
     * Object Property http://owl.man.ac.uk/2006/07/sssw/people#eats
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property EATS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_EATS = factory.getOWLObjectProperty(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#eats"));

    /* ***************************************************
     * Object Property http://owl.man.ac.uk/2006/07/sssw/people#has_child
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_CHILD.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_CHILD = factory.getOWLObjectProperty(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#has_child"));

    /* ***************************************************
     * Object Property http://owl.man.ac.uk/2006/07/sssw/people#has_father
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_FATHER.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_FATHER = factory.getOWLObjectProperty(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#has_father"));

    /* ***************************************************
     * Object Property http://owl.man.ac.uk/2006/07/sssw/people#has_mother
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_MOTHER.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_MOTHER = factory.getOWLObjectProperty(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#has_mother"));

    /* ***************************************************
     * Object Property http://owl.man.ac.uk/2006/07/sssw/people#has_parent
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_PARENT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_PARENT = factory.getOWLObjectProperty(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#has_parent"));

    /* ***************************************************
     * Object Property http://owl.man.ac.uk/2006/07/sssw/people#has_part
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_PART.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_PART = factory.getOWLObjectProperty(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#has_part"));

    /* ***************************************************
     * Object Property http://owl.man.ac.uk/2006/07/sssw/people#has_pet
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_PET.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_PET = factory.getOWLObjectProperty(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#has_pet"));

    /* ***************************************************
     * Object Property http://owl.man.ac.uk/2006/07/sssw/people#is_pet_of
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_PET_OF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_PET_OF = factory.getOWLObjectProperty(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#is_pet_of"));

    /* ***************************************************
     * Object Property http://owl.man.ac.uk/2006/07/sssw/people#likes
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property LIKES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_LIKES = factory.getOWLObjectProperty(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#likes"));

    /* ***************************************************
     * Object Property http://owl.man.ac.uk/2006/07/sssw/people#part_of
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property PART_OF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_PART_OF = factory.getOWLObjectProperty(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#part_of"));

    /* ***************************************************
     * Object Property http://owl.man.ac.uk/2006/07/sssw/people#reads
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property READS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_READS = factory.getOWLObjectProperty(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#reads"));

    /* ***************************************************
     * Object Property http://owl.man.ac.uk/2006/07/sssw/people#works_for
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property WORKS_FOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_WORKS_FOR = factory.getOWLObjectProperty(IRI.create("http://owl.man.ac.uk/2006/07/sssw/people#works_for"));


}
