package travel;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: BudgetAccommodation <br>
 * @version generated on Sun May 16 18:22:29 IST 2021 by ayushyadav
 */

public interface BudgetAccommodation extends Accommodation {

    /* ***************************************************
     * Property http://www.owl-ontologies.com/travel.owl#hasRating
     */
     
    /**
     * Gets all property values for the hasRating property.<p>
     * 
     * @returns a collection of values for the hasRating property.
     */
    Collection<? extends AccommodationRating> getHasRating();

    /**
     * Checks if the class has a hasRating property value.<p>
     * 
     * @return true if there is a hasRating property value.
     */
    boolean hasHasRating();

    /**
     * Adds a hasRating property value.<p>
     * 
     * @param newHasRating the hasRating property value to be added
     */
    void addHasRating(AccommodationRating newHasRating);

    /**
     * Removes a hasRating property value.<p>
     * 
     * @param oldHasRating the hasRating property value to be removed.
     */
    void removeHasRating(AccommodationRating oldHasRating);


    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
