package travel;



import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Sun May 16 18:22:29 IST 2021 by ayushyadav
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://www.owl-ontologies.com/travel.owl#Accommodation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ACCOMMODATION.<p>
     * 
     */
    public static final OWLClass CLASS_ACCOMMODATION = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/travel.owl#Accommodation"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/travel.owl#AccommodationRating
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ACCOMMODATIONRATING.<p>
     * 
     */
    public static final OWLClass CLASS_ACCOMMODATIONRATING = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/travel.owl#AccommodationRating"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/travel.owl#Activity
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ACTIVITY.<p>
     * 
     */
    public static final OWLClass CLASS_ACTIVITY = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/travel.owl#Activity"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/travel.owl#Adventure
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ADVENTURE.<p>
     * 
     */
    public static final OWLClass CLASS_ADVENTURE = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/travel.owl#Adventure"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/travel.owl#BackpackersDestination
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BACKPACKERSDESTINATION.<p>
     * 
     */
    public static final OWLClass CLASS_BACKPACKERSDESTINATION = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/travel.owl#BackpackersDestination"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/travel.owl#Beach
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BEACH.<p>
     * 
     */
    public static final OWLClass CLASS_BEACH = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/travel.owl#Beach"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/travel.owl#BedAndBreakfast
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BEDANDBREAKFAST.<p>
     * 
     */
    public static final OWLClass CLASS_BEDANDBREAKFAST = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/travel.owl#BedAndBreakfast"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/travel.owl#BudgetAccommodation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BUDGETACCOMMODATION.<p>
     * 
     */
    public static final OWLClass CLASS_BUDGETACCOMMODATION = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/travel.owl#BudgetAccommodation"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/travel.owl#BudgetHotelDestination
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BUDGETHOTELDESTINATION.<p>
     * 
     */
    public static final OWLClass CLASS_BUDGETHOTELDESTINATION = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/travel.owl#BudgetHotelDestination"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/travel.owl#BunjeeJumping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BUNJEEJUMPING.<p>
     * 
     */
    public static final OWLClass CLASS_BUNJEEJUMPING = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/travel.owl#BunjeeJumping"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/travel.owl#Campground
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CAMPGROUND.<p>
     * 
     */
    public static final OWLClass CLASS_CAMPGROUND = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/travel.owl#Campground"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/travel.owl#Capital
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CAPITAL.<p>
     * 
     */
    public static final OWLClass CLASS_CAPITAL = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/travel.owl#Capital"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/travel.owl#City
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CITY.<p>
     * 
     */
    public static final OWLClass CLASS_CITY = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/travel.owl#City"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/travel.owl#Contact
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONTACT.<p>
     * 
     */
    public static final OWLClass CLASS_CONTACT = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/travel.owl#Contact"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/travel.owl#Destination
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DESTINATION.<p>
     * 
     */
    public static final OWLClass CLASS_DESTINATION = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/travel.owl#Destination"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/travel.owl#FamilyDestination
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FAMILYDESTINATION.<p>
     * 
     */
    public static final OWLClass CLASS_FAMILYDESTINATION = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/travel.owl#FamilyDestination"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/travel.owl#Farmland
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FARMLAND.<p>
     * 
     */
    public static final OWLClass CLASS_FARMLAND = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/travel.owl#Farmland"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/travel.owl#Hiking
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HIKING.<p>
     * 
     */
    public static final OWLClass CLASS_HIKING = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/travel.owl#Hiking"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/travel.owl#Hotel
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HOTEL.<p>
     * 
     */
    public static final OWLClass CLASS_HOTEL = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/travel.owl#Hotel"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/travel.owl#LuxuryHotel
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LUXURYHOTEL.<p>
     * 
     */
    public static final OWLClass CLASS_LUXURYHOTEL = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/travel.owl#LuxuryHotel"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/travel.owl#Museums
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MUSEUMS.<p>
     * 
     */
    public static final OWLClass CLASS_MUSEUMS = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/travel.owl#Museums"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/travel.owl#NationalPark
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NATIONALPARK.<p>
     * 
     */
    public static final OWLClass CLASS_NATIONALPARK = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/travel.owl#NationalPark"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/travel.owl#QuietDestination
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class QUIETDESTINATION.<p>
     * 
     */
    public static final OWLClass CLASS_QUIETDESTINATION = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/travel.owl#QuietDestination"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/travel.owl#Relaxation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RELAXATION.<p>
     * 
     */
    public static final OWLClass CLASS_RELAXATION = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/travel.owl#Relaxation"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/travel.owl#RetireeDestination
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RETIREEDESTINATION.<p>
     * 
     */
    public static final OWLClass CLASS_RETIREEDESTINATION = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/travel.owl#RetireeDestination"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/travel.owl#RuralArea
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RURALAREA.<p>
     * 
     */
    public static final OWLClass CLASS_RURALAREA = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/travel.owl#RuralArea"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/travel.owl#Safari
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SAFARI.<p>
     * 
     */
    public static final OWLClass CLASS_SAFARI = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/travel.owl#Safari"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/travel.owl#Sightseeing
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SIGHTSEEING.<p>
     * 
     */
    public static final OWLClass CLASS_SIGHTSEEING = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/travel.owl#Sightseeing"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/travel.owl#Sports
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SPORTS.<p>
     * 
     */
    public static final OWLClass CLASS_SPORTS = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/travel.owl#Sports"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/travel.owl#Sunbathing
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SUNBATHING.<p>
     * 
     */
    public static final OWLClass CLASS_SUNBATHING = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/travel.owl#Sunbathing"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/travel.owl#Surfing
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SURFING.<p>
     * 
     */
    public static final OWLClass CLASS_SURFING = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/travel.owl#Surfing"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/travel.owl#Town
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TOWN.<p>
     * 
     */
    public static final OWLClass CLASS_TOWN = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/travel.owl#Town"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/travel.owl#UrbanArea
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class URBANAREA.<p>
     * 
     */
    public static final OWLClass CLASS_URBANAREA = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/travel.owl#UrbanArea"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/travel.owl#Yoga
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class YOGA.<p>
     * 
     */
    public static final OWLClass CLASS_YOGA = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/travel.owl#Yoga"));

    /* ***************************************************
     * Object Property http://www.owl-ontologies.com/travel.owl#hasAccommodation
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASACCOMMODATION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASACCOMMODATION = factory.getOWLObjectProperty(IRI.create("http://www.owl-ontologies.com/travel.owl#hasAccommodation"));

    /* ***************************************************
     * Object Property http://www.owl-ontologies.com/travel.owl#hasActivity
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASACTIVITY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASACTIVITY = factory.getOWLObjectProperty(IRI.create("http://www.owl-ontologies.com/travel.owl#hasActivity"));

    /* ***************************************************
     * Object Property http://www.owl-ontologies.com/travel.owl#hasContact
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASCONTACT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASCONTACT = factory.getOWLObjectProperty(IRI.create("http://www.owl-ontologies.com/travel.owl#hasContact"));

    /* ***************************************************
     * Object Property http://www.owl-ontologies.com/travel.owl#hasPart
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASPART.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASPART = factory.getOWLObjectProperty(IRI.create("http://www.owl-ontologies.com/travel.owl#hasPart"));

    /* ***************************************************
     * Object Property http://www.owl-ontologies.com/travel.owl#hasRating
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASRATING.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASRATING = factory.getOWLObjectProperty(IRI.create("http://www.owl-ontologies.com/travel.owl#hasRating"));

    /* ***************************************************
     * Object Property http://www.owl-ontologies.com/travel.owl#isOfferedAt
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISOFFEREDAT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISOFFEREDAT = factory.getOWLObjectProperty(IRI.create("http://www.owl-ontologies.com/travel.owl#isOfferedAt"));

    /* ***************************************************
     * Data Property http://www.owl-ontologies.com/travel.owl#hasCity
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASCITY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASCITY = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/travel.owl#hasCity"));

    /* ***************************************************
     * Data Property http://www.owl-ontologies.com/travel.owl#hasEMail
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASEMAIL.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASEMAIL = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/travel.owl#hasEMail"));

    /* ***************************************************
     * Data Property http://www.owl-ontologies.com/travel.owl#hasStreet
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASSTREET.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASSTREET = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/travel.owl#hasStreet"));

    /* ***************************************************
     * Data Property http://www.owl-ontologies.com/travel.owl#hasZipCode
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASZIPCODE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASZIPCODE = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/travel.owl#hasZipCode"));


}
